name: collegemitra
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^6.0.0
  get: ^4.6.5
  liquid_swipe: ^3.0.0
  smooth_page_indicator: ^1.0.0+2
  carousel_slider: ^4.2.1
  youtube_player_flutter: ^8.1.2
  flutter_otp_text_field: ^1.1.1
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  stream_channel: ^2.1.1
  firebase_core_platform_interface: ^4.8.0
  cloud_firestore: ^4.9.1
  email_validator: '^2.1.16'
  google_sign_in: ^6.1.5
  line_awesome_flutter: ^2.0.0
  flutter_rating_bar: ^4.0.1
  excel: ^2.1.0
  ionicons: ^0.1.2
  jitsi_meet_flutter_sdk: ^0.1.8
  rive: ^0.12.3
  flutter_svg: ^1.1.6
  animated_custom_dropdown: ^2.0.0
  flutter_native_splash: ^2.3.6
  easy_loader: ^2.0.0
  flutter_lints: ^2.0.3
  tuple: ^2.0.2
  rounded_expansion_tile: ^0.0.13
  supabase_flutter: ^1.10.25

  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo/logo.png
    - assets/images/splash_images/splash-top-icon.png
    - assets/images/splash_images/splash-screen-image.png
    - assets/images/on_boarding_images/on-boarding-image-1.png
    - assets/images/on_boarding_images/on-boarding-image-2.png
    - assets/images/on_boarding_images/on-boarding-image-3.png
    - assets/images/welcome_images/welcome-screen-image.png
    - assets/logo/google-logo.png
    - assets/logo/signup-logo.png
    - assets/logo/forgot-password.png
    - assets/images/dashboard_images/hero_section.png
    - assets/images/dashboard_images/nta.png
    - assets/images/dashboard_images/counselling_images/hstes.png
    - assets/images/dashboard_images/counselling_images/uptu.png
    - assets/images/dashboard_images/counselling_images/ojee.png
    - assets/images/dashboard_images/counselling_images/reap.png
    - assets/images/dashboard_images/counselling_images/josaa.png
    - assets/images/dashboard_images/counselling_images/jacd.png
    - assets/images/dashboard_images/counselling_images/ggsipu.png
    - assets/images/dashboard_images/counselling_images/more.png
    - assets/images/features_images/about.jpeg
    - assets/images/profile_images/profile-image.jpeg
    - assets/images/dashboard_images/t10delhi.jpg
    - assets/images/dashboard_images/support.png
    - assets/images/dashboard_images/background.png
    - assets/images/dashboard_images/background.jpeg
    - assets/images/dashboard_images/graduation.png
    - assets/images/dashboard_images/background_new.png
    - assets/images/dashboard_images/reminder.png
    - assets/images/dashboard_images/3d-fire.png
    - assets/images/dashboard_images/3d-target.png
    - assets/images/dashboard_images/love.png
    - assets/images/dashboard_images/shield.png
    - assets/images/dashboard_images/chart.png
    - assets/images/dashboard_images/bachelors-degree.png
    - assets/images/dashboard_images/benchmarking.png
    - assets/images/dashboard_images/justice-scale.png
    - assets/images/dashboard_images/justice.png
    - assets/images/dashboard_images/office.png
    - assets/images/dashboard_images/ranking.png
    - assets/images/dashboard_images/search.png
    - assets/images/dashboard_images/seats.png
    - assets/cutoff_files/JOSAA_2023.xlsx
    - assets/cutoff_files/CSAB_2023.xlsx
    - assets/images/facebook.png
    - assets/images/spline.png
    - assets/images/riveAssets/shapes.riv
    - assets/images/riveAssets/button.riv
    - assets/images/riveAssets/cartoon.riv
    - assets/images/splash_images/background.png
    - assets/gif/happy.gif
    - assets/gif/sad.gif
    - assets/gif/love.gif
    - assets/gif/neutral.gif
    - assets/gif/faq.gif
    - assets/gif/graduation-cap.gif
    - assets/gif/loader.gif
    - assets/gif/home_loader.gif

flutter_native_splash:
  image: 'assets/images/splash_images/background.png'
  color: "#FFFFFF"


  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
