// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf94ODQdi3Mu6YBANkL6FMu1V4qOnhjjE',
    appId: '1:288462781480:web:d6b9c9f3a9c10e9ebd491d',
    messagingSenderId: '288462781480',
    projectId: 'collegemitra-app',
    authDomain: 'collegemitra-app.firebaseapp.com',
    storageBucket: 'collegemitra-app.appspot.com',
    measurementId: 'G-VC80XP0BRY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFcJxMvVWRA5TQv9YpKKVR_l23JBx7hpo',
    appId: '1:288462781480:android:14b1de187019c295bd491d',
    messagingSenderId: '288462781480',
    projectId: 'collegemitra-app',
    storageBucket: 'collegemitra-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB56j7VTv0hHlxvEm3RNoZaw9ENtQw0UdI',
    appId: '1:288462781480:ios:c950edac716aa7f7bd491d',
    messagingSenderId: '288462781480',
    projectId: 'collegemitra-app',
    storageBucket: 'collegemitra-app.appspot.com',
    iosBundleId: 'com.example.collegemitra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB56j7VTv0hHlxvEm3RNoZaw9ENtQw0UdI',
    appId: '1:288462781480:ios:57f78fef01c39037bd491d',
    messagingSenderId: '288462781480',
    projectId: 'collegemitra-app',
    storageBucket: 'collegemitra-app.appspot.com',
    iosBundleId: 'com.example.collegemitra.RunnerTests',
  );
}
